spring.application.name=PRODUCT-SERVICE
server.port=8081
spring.datasource.url= jdbc:mysql://localhost:3306/vem_produit?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BTlfo9malmo9atila10#
spring.jpa.hibernate.ddl-auto=update
spring.cloud.discovery.enabled=false

