spring.application.name=STOCK-SERVICE
server.port=8082
spring.datasource.url= jdbc:mysql://localhost:3306/vem_stock?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nouha@@123
spring.jpa.hibernate.ddl-auto=update
spring.cloud.discovery.enabled=true