spring.application.name=PREISION-SERVICE
server.port=8083
spring.datasource.url= jdbc:mysql://localhost:3306/vem_prevision?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BTlfo9malmo9atila10#
spring.jpa.hibernate.ddl-auto=create
spring.cloud.discovery.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ecom-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ecom-app/protocol/openid-connect/certs


